#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
app:
  host-url: ${host_url}
  test-mail: ${mail}
spring:
  datasource:
    url: ${db_url}
    username: ${db_name}
    password: ${db_pass}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${oauth2_client_id_git}
            client-secret: ${oauth2_client_secret_git}
            scope:
              - email
          google:
            client-id: ${oauth2_client_id_google}
            client-secret: ${oauth2_client_secret_google}
            scope:
              - email
              - profile
          gitlab:
            client-id: ${oauth2_client_id_gitlab}
            client-secret: ${oauth2_client_secret_gitlab}
            client-name: ${oauth2_client_name_gitlab}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: read_user
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            user-name-attribute: email

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: ${mail_host}
    username: ${mail}
    password: ${mail_password}
    port: ${mail_port}